import { ipcRenderer } from "electron";

export const gitApi = {
  getBranches: () => ipcRenderer.invoke("git:getBranches"),
  checkout: (projectPath: string, branch: string) => ipcRenderer.invoke("git:checkout", projectPath, branch),
  createBranch: (projectPath: string, branch: string) => ipcRenderer.invoke("git:createBranch", projectPath, branch),
  createBranchFrom: (projectPath: string, branch: string, fromBranch: string) => ipcRenderer.invoke("git:createBranchFrom", projectPath, branch, fromBranch),
  updateGitignore: (filePatterns: string | string[], rootDir?: string) =>ipcRenderer.invoke("git:updateGitignore", filePatterns, rootDir),
  diffBranches: (baseBranch: string, compareBranch: string) => ipcRenderer.invoke("git:diffBranches", baseBranch, compareBranch),
  diffFile: (baseBranch: string, compareBranch: string, filePath: string) => ipcRenderer.invoke("git:diffFile", baseBranch, compareBranch, filePath),
  getFileAtBranch: (branch: string, filePath: string) => ipcRenderer.invoke("git:getFileAtBranch", branch, filePath),
  getRepoRoot: () => ipcRenderer.invoke("git:getRepoRoot"),
  getStatus: () => ipcRenderer.invoke("git:getStatus"),
  initialize: () => ipcRenderer.invoke("git:initialize"),
  clone: (repoUrl: string, token?: string) => ipcRenderer.invoke("git:clone", repoUrl, token),
  stage: (files: string[]) => ipcRenderer.invoke("git:stage", files),
  unstage: (files: string[]) => ipcRenderer.invoke("git:unstage", files),
  commit: (message: string) => ipcRenderer.invoke("git:commit", message),
  discard: (files: string[]) => ipcRenderer.invoke("git:discard", files),
  getLog: (limit?: number) => ipcRenderer.invoke("git:getLog", limit),
  getCommitFiles: (commitHash: string) => ipcRenderer.invoke("git:getCommitFiles", commitHash),
  fetchRemote: () => ipcRenderer.invoke("git:fetch"),
  push: () => ipcRenderer.invoke("git:pushBranch"),
  pull: () => ipcRenderer.invoke("git:pull"),
  getRemoteUrl: () => ipcRenderer.invoke("git:getRemoteUrl"),
  setRemoteUrl: (remoteUrl: string) => ipcRenderer.invoke("git:setRemoteUrl", remoteUrl),
  removeRemote: () => ipcRenderer.invoke("git:removeRemote"),
  stash: (message?: string) => ipcRenderer.invoke("git:stash", message),
  stashList: () => ipcRenderer.invoke("git:stashList"),
  stashPop: (index: number) => ipcRenderer.invoke("git:stashPop", index),
  getConflicts: () => ipcRenderer.invoke("git:getConflicts"),
  resolveConflict: (file: string, resolution: 'current' | 'incoming' | 'both', sectionIndex?: number) =>
    ipcRenderer.invoke("git:resolveConflict", file, resolution, sectionIndex),
  getFileContent: (file: string) => ipcRenderer.invoke("git:getFileContent", file),
  saveResolvedFile: (file: string, content: string) => ipcRenderer.invoke("git:saveResolvedFile", file, content),
  uncommit: () => ipcRenderer.invoke("git:uncommit"),
};
